### PR TITLE
Disable reporting if DSN is not set

### PR DESCRIPTION
**Pull request by mbudde**

### CODE REVIEW

**Comment by pmb0** [comment]
Thanks!

**Comment by rabbiveesh** [comment]
hey, the change to `sample` breaks existing code really badly - anything that created a transaction now suddenly gets undef during testing. One of the commits in #30 fixes this.
Unless i'm not understanding something, it never tried reporting anything when there's no dsn; i've been using this for years and in tests i have no DSN and everything is hunky-dory.

**Comment by rabbiveesh** [comment]
In fact, i had already written this behavior in #6 ; what wasn't working about that?

**Comment by mbudde** [comment]
> In fact, i had already written this behavior in #6 ; what wasn't working about that?

The motivation is having a way to completely disable Sentry::SDK (integrations should not be initialized) such that `Sentry::SDK->capture_exeception` et al are just no-ops and there are no potential side-effects (performance or bugs) from the integrations. But looking at the Python SDK it looks like it is handled by having a default no-op client before initialization and if an empty DSN is set the SDK is initialized but doesn't send events. That might be a better way to do it.

**Comment by rabbiveesh** [comment]
Oh, so then this is the wrong thing to do b/c this breaks any integration that was starting a transaction.
If you wanna disable the integrations, then just don't always load them. in #31 I implement this (it matches better to other SDKs where there's a `defaultIntegrations` function exported)

**Pull request merged**
